### ISSUE TITLE
Using --nixos-path doesn't seem to work

### ISSUE THREAD

**Issue by DavHau** [erikarvstedt/extra-container#12] opened 2020-07-26 09:16 UTC
```
$ sudo extra-container create --nixos-path /home/grmpf/synced/projects/github/nixpkgs/nixos --start < nc-extra.nix
Building containers...
error: The option `containers' defined in `/tmp/tmp.b2Ze7rla5Z/container-cfg.nix' does not exist.
(use '--show-trace' to show detailed location information)
```

using `--nixos-path` the same way with nixos-container works

**Comment by erikarvstedt** [comment] 2020-11-01 13:26
This was caused by incompatibility with newer nixpkgs versions.
Fixed in release `0.5`.

**Closed as completed by erikarvstedt** 2020-11-01 13:26 UTC
